services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/analytics.db
    volumes:
      - ./data:/data

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=prod
      - APP_SECRET=5f8a3e7c9d2b1a4f6e8c3d7b9a2e5f1c
      - DB_PATH=/data/analytics.db
    volumes:
      - ./data:/data
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - analytics

volumes:
  data:
