parameters:
    database_path: '%env(default::DB_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Service\DatabaseConnection:
        arguments:
            $dbPath: '%database_path%'
